- hosts: linuxtemplate
  vars_files:
  # User defined variables for infrastructure
   - main_vars.yml  
  roles:
   - role: oracleclient19c_install
   - role: oraclesoft
     become_method: su
     su_user: '{{ oracle_user }}'
     ansible_become_pass: '{{ oracle_os_user_pass }}'
